### ISSUE TITLE
MID Server JAR File missing

### ISSUE THREAD

**Issue by FaresKi** [JefMuller/HashiCorpVaultCredentialResolver#1]
Hello,

My MID JAR file is indicating that some classes are missing, could you provide me with the mid.jar file you used for your code?

Thanks in advance,
Fares

**Comment by JefMuller** [comment]
Hi Fares,
The mid.jar is located in the ServiceNow Mid installation folder. Under agent/lib

**Comment by FaresKi** [comment]
Hi Jeff, 
I'm using the /agent/lib/mid.jar, yet I keep getting this issue : 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/46092308/95770790-39e9b500-0cba-11eb-9799-a068829e1904.png">

I'm using the New York mid.jar, which version did you use?

**Comment by JefMuller** [comment]
I used Orlando. Try the attached one
[mid.jar.zip](https://github.com/JefMuller/HashiCorpVaultCredentialResolver/files/5366485/mid.jar.zip)

**Comment by FaresKi** [comment]
Really weird.
I keep getting this issue : ""main" java.lang.NoClassDefFoundError: com/glideapp/ecc/IECC »

Even when I check the JAR, these files are missing.
Le 12 oct. 2020 à 19:13, JF Muller <notifications@github.com<mailto:notifications@github.com>> a écrit :

mid.jar.zip<https://github.com/JefMuller/HashiCorpVaultCredentialResolver/files/5366485/mid.jar.zip>

**Comment by JefMuller** [comment]
Which SDK are u using? 
I could suggest a zoom session. Just send me your email. (tmrw)

**Comment by FaresKi** [comment]
I’m using the JDK 1.8
I’m interested in the zoom session : kissoumfares@gmail.com
